[package]
name = "curve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#nash-mpc = "1.2.4"
#rust-bigint = "1.2.0"
k256 = "0.11.6"
num = "0.4"

pbkdf2 = "0.11.0"